# o docker compose é um orquestrador de containers dentro do docker, ele define como cada container vai
#se comunicar dentro da aplicação e muito mais!

version: "3"

services: 
  app: 
   build: .
   command: yarn start
   ports: 
    - 3000:3000
   volumes: 
    - .:/usr/app